### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by nachifur** [DreamtaleCore/USI3D#1]
Thank you for your wonderful work and detailed code! But I found some errors, when I used your command line in readme.
## 1. error 1-"train.py", line 55
```
python3 train.py -c configs/intrinsic_MPI.yaml -o checkpoints/ -g 0
/home/liu/Desktop/shadow_removal/reference/USI3D-master/utils.py:116: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(stream)
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    train_loader, test_loader = get_intrinsic_data_loader(config, is_sup=opts.is_sup, rate=intrinsic_rate)
AttributeError: 'Namespace' object has no attribute 'is_sup'
```

##2. error 2-utils.py", line 51
```
python3 train.py -c configs/intrinsic_MPI.yaml -o checkpoints/ -g 0
  File "/home/liu/de/shadow_removal/reference/USI3D-master/train.py", line 56, in <module>
    train_loader, test_loader = get_intrinsic_data_loader(config, is_sup=opts.is_sup, rate=intrinsic_rate)
  File "/home/liu/Desktop/shadow_removal/reference/USI3D-master/utils.py", line 51, in get_intrinsic_data_loader
    raise ValueError('dataset name error in config file: {}'.format(conf['dataset_name']))
ValueError: dataset name error in config file: MPI
```

##3. error 2-"trainer.py", line 227(`refl_smooth_w not in yaml`)
```
  File "/home/liu/Desktop/shadow_removal/reference/USI3D-master/train.py", line 95, in <module>
    trainer.gen_update(images_i, images_r, images_s, targets, config)
  File "/home/liu/Desktop/shadow_removal/reference/USI3D-master/trainer.py", line 227, in gen_update
    param['refl_smooth_w'] * self.loss_refl_ri + \
KeyError: 'refl_smooth_w'
```
Looking forward to your reply!

**Comment by DreamtaleCore** [comment]
Thanks for your interest in our work. 

As for issues 1-2, I will update the corresponding code later.
`refl_smooth_w` is the weight for reflectance smoothness (Eq.11), you can add this parameter in `config.yaml` and set it to 1.0.

best,

**Comment by avani17101** [comment]
There are other parameters like kl_w, kl etc apart from refl_smooth_w which are missing.

**Comment by JakeXin7** [comment]
Hi, thank you for your work!
I still got the errors above, have you solved this problem?

**Comment by Least1924** [comment]
hi,any progress in this problem?

**Comment by daqiudi** [comment]
> hi,any progress in this problem?

can you deal with 1-2 bug ?
